ALTER TABLE customers
    ADD COLUMN IF NOT EXISTS product_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS purchase_amount NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS purchase_date DATE DEFAULT CURRENT_DATE;